/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@forgetcase/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAssessmentsDomainModule,
  buildCasesDomainModule,
  buildCorrespondenceDomainModule,
  buildFulfilmentDomainModule,
  buildIdentityDomainModule,
  buildSlaDomainModule,
} from "../domains/index.js";
import type {
  AssessmentsDomainModule,
  CasesDomainModule,
  CorrespondenceDomainModule,
  FulfilmentDomainModule,
  IdentityDomainModule,
  SlaDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private assessmentsModule: AssessmentsDomainModule | null = null;
  private casesModule: CasesDomainModule | null = null;
  private correspondenceModule: CorrespondenceDomainModule | null = null;
  private fulfilmentModule: FulfilmentDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private slaModule: SlaDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get assessments domain module
   */
  getAssessmentsDependencies(): AssessmentsDomainModule {
    if (!this.assessmentsModule) {
      this.assessmentsModule = buildAssessmentsDomainModule(this.dynamoClient);
    }
    return this.assessmentsModule;
  }

  /**
   * Get cases domain module
   */
  getCasesDependencies(): CasesDomainModule {
    if (!this.casesModule) {
      this.casesModule = buildCasesDomainModule(this.dynamoClient);
    }
    return this.casesModule;
  }

  /**
   * Get correspondence domain module
   */
  getCorrespondenceDependencies(): CorrespondenceDomainModule {
    if (!this.correspondenceModule) {
      this.correspondenceModule = buildCorrespondenceDomainModule(this.dynamoClient);
    }
    return this.correspondenceModule;
  }

  /**
   * Get fulfilment domain module
   */
  getFulfilmentDependencies(): FulfilmentDomainModule {
    if (!this.fulfilmentModule) {
      this.fulfilmentModule = buildFulfilmentDomainModule(this.dynamoClient);
    }
    return this.fulfilmentModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get sla domain module
   */
  getSlaDependencies(): SlaDomainModule {
    if (!this.slaModule) {
      this.slaModule = buildSlaDomainModule(this.dynamoClient);
    }
    return this.slaModule;
  }

  clearAssessmentsDependencies(): void { this.assessmentsModule = null; }
  clearCasesDependencies(): void { this.casesModule = null; }
  clearCorrespondenceDependencies(): void { this.correspondenceModule = null; }
  clearFulfilmentDependencies(): void { this.fulfilmentModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearSlaDependencies(): void { this.slaModule = null; }

  getAssessmentsDependenciesForRequest(): AssessmentsDomainModule {
    return this.getAssessmentsDependencies();
  }

  getCasesDependenciesForRequest(): CasesDomainModule {
    return this.getCasesDependencies();
  }

  getCorrespondenceDependenciesForRequest(): CorrespondenceDomainModule {
    return this.getCorrespondenceDependencies();
  }

  getFulfilmentDependenciesForRequest(): FulfilmentDomainModule {
    return this.getFulfilmentDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getSlaDependenciesForRequest(): SlaDomainModule {
    return this.getSlaDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.assessmentsModule = null;
    this.casesModule = null;
    this.correspondenceModule = null;
    this.fulfilmentModule = null;
    this.identityModule = null;
    this.slaModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
