/**
 * GetAssessment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetGroundAssessmentParams } from "@forgetcase/core/assessments";

export function createGetAssessmentRequest(overrides: Partial<GetGroundAssessmentParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
