/**
 * SendCaseCorrespondence handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: correspondence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { sendCaseCorrespondence } from "@forgetcase/api-server/domains/correspondence/handlers";
import type { CorrespondenceDDDDependencies } from "@forgetcase/api-server/domains/correspondence";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@forgetcase/tests/shared";
import { CORRESPONDENCE_USE_CASES } from "../__factories__/use-cases.js";

describe("SendCaseCorrespondence", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CorrespondenceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CorrespondenceDDDDependencies>(
      CORRESPONDENCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSendCaseCorrespondence, "execute").mockResolvedValue(useCaseResult);

    await sendCaseCorrespondence(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSendCaseCorrespondence.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
