/**
 * Assessments DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assessments Domain Module - Composition root
 *
 * DDD: Composition root for assessments domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AssessmentRepositoryAdapter,
  ExemptionRepositoryAdapter,
} from "@forgetcase/adapters/assessments";
import { getIdGeneratorService } from "@forgetcase/adapters";
import type { AdapterDynamoDBClient } from "@forgetcase/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApplyExemption,
  ExecuteGetGroundAssessment,
  ExecuteListExemptions,
  ExecuteSubmitGroundAssessment,
} from "@forgetcase/services/assessments/usecases";
// Ports (interfaces)
import type {
  AssessmentRepository,
  ExemptionRepository,
} from "@forgetcase/services/assessments/ports";

export interface AssessmentsDomainModule {
  repos: {
    assessments: AssessmentRepository;
    exemptions: ExemptionRepository;
  };
  useCases: {
    assessments: {
      create: ExecuteSubmitGroundAssessment;
      get: ExecuteGetGroundAssessment;
    };
    exemptions: {
      get: ExecuteApplyExemption;
      list: ExecuteListExemptions;
    };
  };
}

export function buildAssessmentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AssessmentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      assessments?: AssessmentRepository;
      exemptions?: ExemptionRepository;
    } = {};

    obj.assessments = new AssessmentRepositoryAdapter(dynamoClient);
    obj.exemptions = new ExemptionRepositoryAdapter(dynamoClient);
    return {
      assessments: obj.assessments!,
      exemptions: obj.exemptions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    assessments: {
      create: new ExecuteSubmitGroundAssessment(executionContext, idGenerator, repos.assessments),
      get: new ExecuteGetGroundAssessment(executionContext, idGenerator, repos.assessments),
    },
    exemptions: {
      get: new ExecuteApplyExemption(executionContext, idGenerator, repos.exemptions),
      list: new ExecuteListExemptions(executionContext, idGenerator, repos.exemptions),
    },
  };
  return { repos, useCases: useCases as AssessmentsDomainModule["useCases"] };
}
