/**
 * ExemptionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExemptionRepository Port
 *
 * DDD: Application port for exemptionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ApplyExemptionInput, ApplyExemptionOutput, ListExemptionsInput, ListExemptionsOutput } from "../dto/exemption.dto";
export interface ExemptionRepository {
  listExemptions(input: ListExemptionsInput): Promise<ListExemptionsOutput>;
  applyExemption(input: ApplyExemptionInput): Promise<ApplyExemptionOutput>;
}

export type { ApplyExemptionInput, ApplyExemptionOutput, ListExemptionsInput, ListExemptionsOutput } from "../dto/exemption.dto";
