/**
 * Routes for BackupBeyondUseTask
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createBackupBeyondUseTask, listBackupBeyondUseTasks } from "../handlers/backup-beyond-use-task.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function backupBeyondUseTaskRoutes(fastify: FastifyInstance) {
  // POST /v1/backup-beyond-use-tasks (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/backup-beyond-use-tasks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFulfilmentDependenciesForRequest();
        await createBackupBeyondUseTask(request, reply, deps);
      });
    }
  );


  // GET /v1/backup-beyond-use-tasks (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/backup-beyond-use-tasks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFulfilmentDependenciesForRequest();
        await listBackupBeyondUseTasks(request, reply, deps);
      });
    }
  );


}
