/**
 * Routes for Complete
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { completeBackupBeyondUseTask, completeLiveErasureTask } from "../handlers/complete.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function completeRoutes(fastify: FastifyInstance) {
  // POST /v1/backup-beyond-use-tasks/{taskId}/complete (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/backup-beyond-use-tasks/:taskId/complete",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { taskId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFulfilmentDependenciesForRequest();
        await completeBackupBeyondUseTask(request, reply, deps);
      });
    }
  );


  // POST /v1/live-erasure-tasks/{taskId}/complete (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/live-erasure-tasks/:taskId/complete",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { taskId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFulfilmentDependenciesForRequest();
        await completeLiveErasureTask(request, reply, deps);
      });
    }
  );


}
