/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { backupBeyondUseTaskRoutes } from "./backup-beyond-use-task.routes.js";
export { completeRoutes } from "./complete.routes.js";
export { liveErasureTaskRoutes } from "./live-erasure-task.routes.js";
export { recipientNoticeRoutes } from "./recipient-notice.routes.js";
