/**
 * Routes for LiveErasureTask
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createLiveErasureTask, listLiveErasureTasks } from "../handlers/live-erasure-task.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function liveErasureTaskRoutes(fastify: FastifyInstance) {
  // POST /v1/erasure-cases/{caseId}/live-erasure-tasks (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/erasure-cases/:caseId/live-erasure-tasks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFulfilmentDependenciesForRequest();
        await createLiveErasureTask(request, reply, deps);
      });
    }
  );


  // GET /v1/erasure-cases/{caseId}/live-erasure-tasks (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/erasure-cases/:caseId/live-erasure-tasks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFulfilmentDependenciesForRequest();
        await listLiveErasureTasks(request, reply, deps);
      });
    }
  );


}
