/**
 * Routes for RecipientNotice
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createRecipientNotice, listRecipientNotices, updateRecipientNotice } from "../handlers/recipient-notice.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function recipientNoticeRoutes(fastify: FastifyInstance) {
  // POST /v1/erasure-cases/{caseId}/recipient-notices (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/erasure-cases/:caseId/recipient-notices",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFulfilmentDependenciesForRequest();
        await createRecipientNotice(request, reply, deps);
      });
    }
  );


  // GET /v1/erasure-cases/{caseId}/recipient-notices (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/erasure-cases/:caseId/recipient-notices",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFulfilmentDependenciesForRequest();
        await listRecipientNotices(request, reply, deps);
      });
    }
  );


  // PATCH /v1/recipient-notices/{noticeId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/recipient-notices/:noticeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { noticeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFulfilmentDependenciesForRequest();
        await updateRecipientNotice(request, reply, deps);
      });
    }
  );


}
