/**
 * Handlers for Exemption
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AssessmentsDomainModule } from "../dependencies/assessments-ddd.dependencies.js";
import type { ApplyExemptionInput, ListExemptionsInput } from "@forgetcase/services/assessments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/erasure-cases/{caseId}/exemptions
 * Operation: listExemptions
 */
export async function listExemptions(
  request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AssessmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListExemptionsInput = {
    caseId: request.params.caseId,
  };
  const result = await deps.useCases.exemptions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/erasure-cases/{caseId}/exemptions
 * Operation: applyExemption
 */
export async function applyExemption(
  request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AssessmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ApplyExemptionInput = {
    caseId: request.params.caseId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.exemptions.get.execute(input);
  return reply.code(201).send(result);
}


