/**
 * Extension DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Extension DTOs
 *
 * DDD: Application DTOs for Extension use cases.
 */

import type { ExtendSlaClockParams, ExtendSlaClockRequestInput } from "@forgetcase/core/sla/types";

export type ExtendSlaClockInput = ExtendSlaClockParams & ExtendSlaClockRequestInput;

export type ExtendSlaClockOutput = {};
