/**
 * IdentityChallenge DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IdentityChallenge DTOs
 *
 * DDD: Application DTOs for IdentityChallenge use cases.
 */

import type { RequestIdentityChallengeParams, RequestIdentityChallengeRequestInput } from "@forgetcase/core/sla/types";

export type RequestIdentityChallengeInput = RequestIdentityChallengeParams & RequestIdentityChallengeRequestInput;

export type RequestIdentityChallengeOutput = {};
