/**
 * Satisfy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Satisfy DTOs
 *
 * DDD: Application DTOs for Satisfy use cases.
 */

import type { SatisfyIdentityChallengeParams, SatisfyIdentityChallengeRequestInput } from "@forgetcase/core/sla/types";

export type SatisfyIdentityChallengeInput = SatisfyIdentityChallengeParams & SatisfyIdentityChallengeRequestInput;

export type SatisfyIdentityChallengeOutput = {};
