/**
 * Sla DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Sla DTOs
 *
 * DDD: Application DTOs for Sla use cases.
 */

import type { GetSlaClockParams } from "@forgetcase/core/sla/types";

export type GetSlaClockInput = GetSlaClockParams;

export type GetSlaClockOutput = {};
