/**
 * ErasureCase Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ErasureCaseEntity } from "@forgetcase/core/cases/models/index.js";
import { casesSchemas } from "@forgetcase/core/cases";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cas";

export function createErasureCase(overrides: Partial<ErasureCaseEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    caseId: overrides.caseId ?? `cas_${ulid().toLowerCase()}`,
    channel: overrides.channel ?? "verbal",
    childDataWeight: overrides.childDataWeight ?? faker.datatype.boolean(),
    dueAt: overrides.dueAt ?? new Date().toISOString(),
    receivedAt: overrides.receivedAt ?? new Date().toISOString(),
    status: overrides.status ?? "intake",
    subjectRef: overrides.subjectRef ?? faker.lorem.word(),
    ...overrides,
  };

  return casesSchemas.ErasureCase.parse(raw);
}

export function erasureCaseBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createErasureCase(overrides));
}
