/**
 * BackupBeyondUseTask DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BackupBeyondUseTask DTOs
 *
 * DDD: Application DTOs for BackupBeyondUseTask use cases.
 */

import type { CreateBackupBeyondUseTaskRequestInput, ListBackupBeyondUseTasksParams } from "@forgetcase/core/fulfilment/types";

export type ListBackupBeyondUseTasksInput = ListBackupBeyondUseTasksParams;

export type CreateBackupBeyondUseTaskInput = CreateBackupBeyondUseTaskRequestInput;

export type ListBackupBeyondUseTasksOutput = {};

export type CreateBackupBeyondUseTaskOutput = {};
