/**
 * Complete DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Complete DTOs
 *
 * DDD: Application DTOs for Complete use cases.
 */

import type { CompleteBackupBeyondUseTaskParams, CompleteBackupBeyondUseTaskRequestInput, CompleteLiveErasureTaskParams, CompleteLiveErasureTaskRequestInput } from "@forgetcase/core/fulfilment/types";

export type CompleteLiveErasureTaskInput = CompleteLiveErasureTaskParams & CompleteLiveErasureTaskRequestInput;

export type CompleteBackupBeyondUseTaskInput = CompleteBackupBeyondUseTaskParams & CompleteBackupBeyondUseTaskRequestInput;

export type CompleteLiveErasureTaskOutput = {};

export type CompleteBackupBeyondUseTaskOutput = {};
