/**
 * LiveErasureTask DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LiveErasureTask DTOs
 *
 * DDD: Application DTOs for LiveErasureTask use cases.
 */

import type { CreateLiveErasureTaskParams, CreateLiveErasureTaskRequestInput, ListLiveErasureTasksParams } from "@forgetcase/core/fulfilment/types";

export type ListLiveErasureTasksInput = ListLiveErasureTasksParams;

export type CreateLiveErasureTaskInput = CreateLiveErasureTaskParams & CreateLiveErasureTaskRequestInput;

export type ListLiveErasureTasksOutput = {};

export type CreateLiveErasureTaskOutput = {};
