/**
 * RecipientNotice DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RecipientNotice DTOs
 *
 * DDD: Application DTOs for RecipientNotice use cases.
 */

import type { CreateRecipientNoticeParams, CreateRecipientNoticeRequestInput, ListRecipientNoticesParams, UpdateRecipientNoticeParams, UpdateRecipientNoticeRequestInput } from "@forgetcase/core/fulfilment/types";

export type ListRecipientNoticesInput = ListRecipientNoticesParams;

export type CreateRecipientNoticeInput = CreateRecipientNoticeParams & CreateRecipientNoticeRequestInput;

export type UpdateRecipientNoticeInput = UpdateRecipientNoticeParams & UpdateRecipientNoticeRequestInput;

export type ListRecipientNoticesOutput = {};

export type CreateRecipientNoticeOutput = {};

export type UpdateRecipientNoticeOutput = {};
