/**
 * Repository interface for ErasureCase
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ErasureCaseEntity
} from "../models/erasure-case.entity.js";
import type {
  ListErasureCasesParams,
  ErasureCase
} from "../types/index.js";
/**
 * ErasureCaseRepository Interface
 */
export interface ErasureCaseRepository extends CreateReadRepository<ErasureCaseEntity, ErasureCase, string, ListErasureCasesParams> {

}
