/**
 * Correspondence DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: correspondence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Correspondence Domain Module - Composition root
 *
 * DDD: Composition root for correspondence domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CorrespondenceRepositoryAdapter,
} from "@forgetcase/adapters/correspondence";
import { getIdGeneratorService } from "@forgetcase/adapters";
import type { AdapterDynamoDBClient } from "@forgetcase/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListCaseCorrespondence,
  ExecuteSendCaseCorrespondence,
} from "@forgetcase/services/correspondence/usecases";
// Ports (interfaces)
import type {
  CorrespondenceRepository,
} from "@forgetcase/services/correspondence/ports";

export interface CorrespondenceDomainModule {
  repos: {
    correspondences: CorrespondenceRepository;
  };
  useCases: {
    correspondences: {
      create: ExecuteSendCaseCorrespondence;
      list: ExecuteListCaseCorrespondence;
    };
  };
}

export function buildCorrespondenceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CorrespondenceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      correspondences?: CorrespondenceRepository;
    } = {};

    obj.correspondences = new CorrespondenceRepositoryAdapter(dynamoClient);
    return {
      correspondences: obj.correspondences!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    correspondences: {
      create: new ExecuteSendCaseCorrespondence(executionContext, idGenerator, repos.correspondences),
      list: new ExecuteListCaseCorrespondence(executionContext, idGenerator, repos.correspondences),
    },
  };
  return { repos, useCases: useCases as CorrespondenceDomainModule["useCases"] };
}
