/**
 * RecipientNotice Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RecipientNoticeEntity } from "@forgetcase/core/fulfilment/models/index.js";
import { fulfilmentSchemas } from "@forgetcase/core/fulfilment";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ffl";

export function createRecipientNotice(overrides: Partial<RecipientNoticeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    caseId: overrides.caseId ?? `cas_${ulid().toLowerCase()}`,
    noticeId: overrides.noticeId ?? `rcn_${ulid().toLowerCase()}`,
    recipientKind: overrides.recipientKind ?? "controller",
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return fulfilmentSchemas.RecipientNotice.parse(raw);
}

export function recipientNoticeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRecipientNotice(overrides));
}
