/**
 * ExecuteListErasureCases - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListErasureCases Use Case
 *
 * DDD: Application use case for list ErasureCase.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListErasureCasesInput, ListErasureCasesOutput } from "../dto/erasure-case.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { ErasureCaseRepository } from "../ports";

export class ExecuteListErasureCases {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly erasureCase: ErasureCaseRepository
  ) {}

  async execute(input: ListErasureCasesInput): Promise<ListErasureCasesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.casId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.erasureCase.listErasureCases({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListErasureCasesOutput;
  }
}
