/**
 * ExecuteListCaseIntakeEvents - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCaseIntakeEvents Use Case
 *
 * DDD: Application use case for list IntakeEvent.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCaseIntakeEventsInput, ListCaseIntakeEventsOutput } from "../dto/intake-event.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { IntakeEventRepository } from "../ports";

export class ExecuteListCaseIntakeEvents {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly intakeEvent: IntakeEventRepository
  ) {}

  async execute(input: ListCaseIntakeEventsInput): Promise<ListCaseIntakeEventsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.casId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.intakeEvent.listCaseIntakeEvents({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCaseIntakeEventsOutput;
  }
}
