/**
 * ExecuteGetErasureCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetErasureCase Use Case
 *
 * DDD: Application use case for get ErasureCase.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetErasureCaseInput, GetErasureCaseOutput } from "../dto/erasure-case.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { ErasureCaseRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetErasureCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly erasureCase: ErasureCaseRepository
  ) {}

  async execute(input: GetErasureCaseInput): Promise<GetErasureCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.casId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).caseId) {
      throw new ValidationError("caseId is required");
    }
    const caseId = (input as any).caseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.erasureCase.getErasureCase({ caseId: caseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${caseId}`);
    }

    return entity as GetErasureCaseOutput;
  }
}
