/**
 * ExecuteCreateVerbalIntake - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateVerbalIntake Use Case
 *
 * DDD: Application use case for create Verbal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateVerbalIntakeInput, CreateVerbalIntakeOutput } from "../dto/verbal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { VerbalRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateVerbalIntake {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly verbal: VerbalRepository
  ) {}

  async execute(input: CreateVerbalIntakeInput): Promise<CreateVerbalIntakeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.casId();

    // All field names extracted from OpenAPI spec: childRelatedHint, dataConcern, readbackConfirmed, requestSummary, saveAsDraft, subjectRef, ticketRef, whoSpoke
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.readbackConfirmed) {
      throw new ValidationError("readbackConfirmed is required");
    }
    if (!input.subjectRef) {
      throw new ValidationError("subjectRef is required");
    }
    if (!input.requestSummary) {
      throw new ValidationError("requestSummary is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (cases domain)
    const entityId = this.idGenerator.casId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.verbal.createVerbalIntake({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateVerbalIntakeOutput;
  }
}
