/**
 * ExecuteCreateErasureCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateErasureCase Use Case
 *
 * DDD: Application use case for create ErasureCase.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateErasureCaseInput, CreateErasureCaseOutput } from "../dto/erasure-case.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { ErasureCaseRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateErasureCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly erasureCase: ErasureCaseRepository
  ) {}

  async execute(input: CreateErasureCaseInput): Promise<CreateErasureCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.casId();

    // All field names extracted from OpenAPI spec: channel, childDataWeight, receivedAt, requestSummary, subjectRef, ticketRef
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.receivedAt) {
      throw new ValidationError("receivedAt is required");
    }
    if (!input.channel) {
      throw new ValidationError("channel is required");
    }
    if (!input.subjectRef) {
      throw new ValidationError("subjectRef is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (cases domain)
    const entityId = this.idGenerator.casId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.erasureCase.createErasureCase({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateErasureCaseOutput;
  }
}
