/**
 * Fulfilment DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Fulfilment Domain Module - Composition root
 *
 * DDD: Composition root for fulfilment domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BackupBeyondUseTaskRepositoryAdapter,
  CompleteRepositoryAdapter,
  LiveErasureTaskRepositoryAdapter,
  RecipientNoticeRepositoryAdapter,
} from "@forgetcase/adapters/fulfilment";
import { getIdGeneratorService } from "@forgetcase/adapters";
import type { AdapterDynamoDBClient } from "@forgetcase/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCompleteBackupBeyondUseTask,
  ExecuteCompleteLiveErasureTask,
  ExecuteCreateBackupBeyondUseTask,
  ExecuteCreateLiveErasureTask,
  ExecuteCreateRecipientNotice,
  ExecuteListBackupBeyondUseTasks,
  ExecuteListLiveErasureTasks,
  ExecuteListRecipientNotices,
  ExecuteUpdateRecipientNotice,
} from "@forgetcase/services/fulfilment/usecases";
// Ports (interfaces)
import type {
  BackupBeyondUseTaskRepository,
  CompleteRepository,
  LiveErasureTaskRepository,
  RecipientNoticeRepository,
} from "@forgetcase/services/fulfilment/ports";

export interface FulfilmentDomainModule {
  repos: {
    backupBeyondUseTasks: BackupBeyondUseTaskRepository;
    completes: CompleteRepository;
    liveErasureTasks: LiveErasureTaskRepository;
    recipientNotices: RecipientNoticeRepository;
  };
  useCases: {
    backupBeyondUseTasks: {
      create: ExecuteCreateBackupBeyondUseTask;
      list: ExecuteListBackupBeyondUseTasks;
    };
    completes: {
      create: ExecuteCompleteBackupBeyondUseTask;
    };
    liveErasureTasks: {
      create: ExecuteCreateLiveErasureTask;
      list: ExecuteListLiveErasureTasks;
    };
    recipientNotices: {
      create: ExecuteCreateRecipientNotice;
      list: ExecuteListRecipientNotices;
      update: ExecuteUpdateRecipientNotice;
    };
  };
}

export function buildFulfilmentDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): FulfilmentDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      backupBeyondUseTasks?: BackupBeyondUseTaskRepository;
      completes?: CompleteRepository;
      liveErasureTasks?: LiveErasureTaskRepository;
      recipientNotices?: RecipientNoticeRepository;
    } = {};

    obj.backupBeyondUseTasks = new BackupBeyondUseTaskRepositoryAdapter(dynamoClient);
    obj.completes = new CompleteRepositoryAdapter(dynamoClient);
    obj.liveErasureTasks = new LiveErasureTaskRepositoryAdapter(dynamoClient);
    obj.recipientNotices = new RecipientNoticeRepositoryAdapter(dynamoClient);
    return {
      backupBeyondUseTasks: obj.backupBeyondUseTasks!,
      completes: obj.completes!,
      liveErasureTasks: obj.liveErasureTasks!,
      recipientNotices: obj.recipientNotices!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    backupBeyondUseTasks: {
      create: new ExecuteCreateBackupBeyondUseTask(executionContext, idGenerator, repos.backupBeyondUseTasks),
      list: new ExecuteListBackupBeyondUseTasks(executionContext, idGenerator, repos.backupBeyondUseTasks),
    },
    completes: {
      create: new ExecuteCompleteBackupBeyondUseTask(executionContext, idGenerator, repos.completes),
    },
    liveErasureTasks: {
      create: new ExecuteCreateLiveErasureTask(executionContext, idGenerator, repos.liveErasureTasks),
      list: new ExecuteListLiveErasureTasks(executionContext, idGenerator, repos.liveErasureTasks),
    },
    recipientNotices: {
      create: new ExecuteCreateRecipientNotice(executionContext, idGenerator, repos.recipientNotices),
      list: new ExecuteListRecipientNotices(executionContext, idGenerator, repos.recipientNotices),
      update: new ExecuteUpdateRecipientNotice(executionContext, idGenerator, repos.recipientNotices),
    },
  };
  return { repos, useCases: useCases as FulfilmentDomainModule["useCases"] };
}
