/**
 * IdentityChallenge Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { IdentityChallengeEntity } from "@forgetcase/core/sla/models/index.js";
import { slaSchemas } from "@forgetcase/core/sla";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "sla";

export function createIdentityChallenge(overrides: Partial<IdentityChallengeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    caseId: overrides.caseId ?? `cas_${ulid().toLowerCase()}`,
    challengeId: overrides.challengeId ?? `idc_${ulid().toLowerCase()}`,
    requestedAt: overrides.requestedAt ?? new Date().toISOString(),
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return slaSchemas.IdentityChallenge.parse(raw);
}

export function identityChallengeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createIdentityChallenge(overrides));
}
