/**
 * IntakeEvent Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { IntakeEventEntity } from "@forgetcase/core/cases/models/index.js";
import { casesSchemas } from "@forgetcase/core/cases";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cas";

export function createIntakeEvent(overrides: Partial<IntakeEventEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    capturedAt: overrides.capturedAt ?? new Date().toISOString(),
    caseId: overrides.caseId ?? `cas_${ulid().toLowerCase()}`,
    channel: overrides.channel ?? "verbal",
    intakeEventId: overrides.intakeEventId ?? `int_${ulid().toLowerCase()}`,
    readbackConfirmed: overrides.readbackConfirmed ?? faker.datatype.boolean(),
    ...overrides,
  };

  return casesSchemas.IntakeEvent.parse(raw);
}

export function intakeEventBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createIntakeEvent(overrides));
}
