/**
 * BackupBeyondUseTask Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { BackupBeyondUseTaskEntity } from "@forgetcase/core/fulfilment/models/index.js";
import { fulfilmentSchemas } from "@forgetcase/core/fulfilment";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ffl";

export function createBackupBeyondUseTask(overrides: Partial<BackupBeyondUseTaskEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    backupSystem: overrides.backupSystem ?? faker.lorem.word(),
    caseId: overrides.caseId ?? `cas_${ulid().toLowerCase()}`,
    status: overrides.status ?? "open",
    taskId: overrides.taskId ?? `bku_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return fulfilmentSchemas.BackupBeyondUseTask.parse(raw);
}

export function backupBeyondUseTaskBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createBackupBeyondUseTask(overrides));
}
