/**
 * Routes for Assessment
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getGroundAssessment, submitGroundAssessment } from "../handlers/assessment.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function assessmentRoutes(fastify: FastifyInstance) {
  // GET /v1/erasure-cases/{caseId}/assessment (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/erasure-cases/:caseId/assessment",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssessmentsDependenciesForRequest();
        await getGroundAssessment(request, reply, deps);
      });
    }
  );


  // POST /v1/erasure-cases/{caseId}/assessment (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/erasure-cases/:caseId/assessment",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssessmentsDependenciesForRequest();
        await submitGroundAssessment(request, reply, deps);
      });
    }
  );


}
