/**
 * Cases DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Cases Domain Module - Composition root
 *
 * DDD: Composition root for cases domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ErasureCaseRepositoryAdapter,
  ExportRepositoryAdapter,
  IntakeEventRepositoryAdapter,
  VerbalRepositoryAdapter,
} from "@forgetcase/adapters/cases";
import { getIdGeneratorService } from "@forgetcase/adapters";
import type { AdapterDynamoDBClient } from "@forgetcase/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateAuditExport,
  ExecuteCreateErasureCase,
  ExecuteCreateVerbalIntake,
  ExecuteGetErasureCase,
  ExecuteListCaseIntakeEvents,
  ExecuteListErasureCases,
} from "@forgetcase/services/cases/usecases";
// Ports (interfaces)
import type {
  ErasureCaseRepository,
  ExportRepository,
  IntakeEventRepository,
  VerbalRepository,
} from "@forgetcase/services/cases/ports";

export interface CasesDomainModule {
  repos: {
    erasureCases: ErasureCaseRepository;
    exports: ExportRepository;
    intakeEvents: IntakeEventRepository;
    verbals: VerbalRepository;
  };
  useCases: {
    erasureCases: {
      create: ExecuteCreateErasureCase;
      get: ExecuteGetErasureCase;
      list: ExecuteListErasureCases;
    };
    exports: {
      create: ExecuteCreateAuditExport;
    };
    intakeEvents: {
      list: ExecuteListCaseIntakeEvents;
    };
    verbals: {
      create: ExecuteCreateVerbalIntake;
    };
  };
}

export function buildCasesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CasesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      erasureCases?: ErasureCaseRepository;
      exports?: ExportRepository;
      intakeEvents?: IntakeEventRepository;
      verbals?: VerbalRepository;
    } = {};

    obj.erasureCases = new ErasureCaseRepositoryAdapter(dynamoClient);
    obj.exports = new ExportRepositoryAdapter(dynamoClient);
    obj.intakeEvents = new IntakeEventRepositoryAdapter(dynamoClient);
    obj.verbals = new VerbalRepositoryAdapter(dynamoClient);
    return {
      erasureCases: obj.erasureCases!,
      exports: obj.exports!,
      intakeEvents: obj.intakeEvents!,
      verbals: obj.verbals!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    erasureCases: {
      create: new ExecuteCreateErasureCase(executionContext, idGenerator, repos.erasureCases),
      get: new ExecuteGetErasureCase(executionContext, idGenerator, repos.erasureCases),
      list: new ExecuteListErasureCases(executionContext, idGenerator, repos.erasureCases),
    },
    exports: {
      create: new ExecuteCreateAuditExport(executionContext, idGenerator, repos.exports),
    },
    intakeEvents: {
      list: new ExecuteListCaseIntakeEvents(executionContext, idGenerator, repos.intakeEvents),
    },
    verbals: {
      create: new ExecuteCreateVerbalIntake(executionContext, idGenerator, repos.verbals),
    },
  };
  return { repos, useCases: useCases as CasesDomainModule["useCases"] };
}
