/**
 * ErasureCaseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ErasureCaseRepository Port
 *
 * DDD: Application port for erasurecaserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateErasureCaseInput, CreateErasureCaseOutput, GetErasureCaseInput, GetErasureCaseOutput, ListErasureCasesInput, ListErasureCasesOutput } from "../dto/erasure-case.dto";
export interface ErasureCaseRepository {
  listErasureCases(input: ListErasureCasesInput): Promise<ListErasureCasesOutput>;
  createErasureCase(input: CreateErasureCaseInput): Promise<CreateErasureCaseOutput>;
  getErasureCase(input: GetErasureCaseInput): Promise<GetErasureCaseOutput>;
}

export type { CreateErasureCaseInput, CreateErasureCaseOutput, GetErasureCaseInput, GetErasureCaseOutput, ListErasureCasesInput, ListErasureCasesOutput } from "../dto/erasure-case.dto";
