/**
 * IntakeEventRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IntakeEventRepository Port
 *
 * DDD: Application port for intakeeventrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListCaseIntakeEventsInput, ListCaseIntakeEventsOutput } from "../dto/intake-event.dto";
export interface IntakeEventRepository {
  listCaseIntakeEvents(input: ListCaseIntakeEventsInput): Promise<ListCaseIntakeEventsOutput>;
}

export type { ListCaseIntakeEventsInput, ListCaseIntakeEventsOutput } from "../dto/intake-event.dto";
