/**
 * VerbalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VerbalRepository Port
 *
 * DDD: Application port for verbalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateVerbalIntakeInput, CreateVerbalIntakeOutput } from "../dto/verbal.dto";
export interface VerbalRepository {
  createVerbalIntake(input: CreateVerbalIntakeInput): Promise<CreateVerbalIntakeOutput>;
}

export type { CreateVerbalIntakeInput, CreateVerbalIntakeOutput } from "../dto/verbal.dto";
