/**
 * Assessment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assessment DTOs
 *
 * DDD: Application DTOs for Assessment use cases.
 */

import type { GetGroundAssessmentParams, SubmitGroundAssessmentParams, SubmitGroundAssessmentRequestInput } from "@forgetcase/core/assessments/types";

export type GetGroundAssessmentInput = GetGroundAssessmentParams;

export type SubmitGroundAssessmentInput = SubmitGroundAssessmentParams & SubmitGroundAssessmentRequestInput;

export type GetGroundAssessmentOutput = {};

export type SubmitGroundAssessmentOutput = {};
