/**
 * Exemption DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Exemption DTOs
 *
 * DDD: Application DTOs for Exemption use cases.
 */

import type { ApplyExemptionParams, ApplyExemptionRequestInput, ListExemptionsParams } from "@forgetcase/core/assessments/types";

export type ListExemptionsInput = ListExemptionsParams;

export type ApplyExemptionInput = ApplyExemptionParams & ApplyExemptionRequestInput;

export type ListExemptionsOutput = {};

export type ApplyExemptionOutput = {};
