/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @forgetcase/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@forgetcase/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@forgetcase/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@forgetcase/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@forgetcase/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@forgetcase/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _assessments from "./assessments/index.js";
import * as _cases from "./cases/index.js";
import * as _correspondence from "./correspondence/index.js";
import * as _fulfilment from "./fulfilment/index.js";
import * as _identity from "./identity/index.js";
import * as _sla from "./sla/index.js";

// Export as namespaces
export const _shared = __shared;
export const assessments = _assessments;
export const cases = _cases;
export const correspondence = _correspondence;
export const fulfilment = _fulfilment;
export const identity = _identity;
export const sla = _sla;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@forgetcase/core"; activity.types.*
//   - Direct exports: import * from "@forgetcase/core/activity/types/index.js"
//   - Direct exports: import * from "@forgetcase/core/activity/repositories/index.js"
//   - Direct exports: import * from "@forgetcase/core/activity/models/index.js"
//   - Direct exports: import * from "@forgetcase/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Assessments Service
export { schemas as AssessmentsSchemas } from "./assessments/schemas/assessments.schemas.js";

// Cases Service
export { schemas as CasesSchemas } from "./cases/schemas/cases.schemas.js";

// Correspondence Service
export { schemas as CorrespondenceSchemas } from "./correspondence/schemas/correspondence.schemas.js";

// Fulfilment Service
export { schemas as FulfilmentSchemas } from "./fulfilment/schemas/fulfilment.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Sla Service
export { schemas as SlaSchemas } from "./sla/schemas/sla.schemas.js";

