/**
 * ListErasureCases handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listErasureCases } from "@forgetcase/api-server/domains/cases/handlers";
import type { CasesDDDDependencies } from "@forgetcase/api-server/domains/cases";
import { createErasureCase as createErasureCaseEntity } from "@forgetcase/factories/cases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@forgetcase/tests/shared";
import { CASES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListErasureCases", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CasesDDDDependencies>(
      CASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createErasureCaseEntity({ orgId }),
      createErasureCaseEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListErasureCases, "execute").mockResolvedValue(useCaseResult);

    await listErasureCases(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListErasureCases.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
