/**
 * BackupBeyondUseTaskRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BackupBeyondUseTaskRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BackupBeyondUseTaskRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BackupBeyondUseTaskRepository,
} from "@forgetcase/services/fulfilment";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BackupBeyondUseTaskRepositoryDdb } from "./backup-beyond-use-task-repository.ddb.js";

/**
 * BackupBeyondUseTaskRepositoryAdapter
 *
 * Implements BackupBeyondUseTaskRepository port for infrastructure layer.
 */
export class BackupBeyondUseTaskRepositoryAdapter implements BackupBeyondUseTaskRepository {
  private readonly ddb: BackupBeyondUseTaskRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BackupBeyondUseTaskRepositoryDdb(this.dynamoClient);
  }

  async listBackupBeyondUseTasks(input: Parameters<BackupBeyondUseTaskRepository['listBackupBeyondUseTasks']>[0]): Promise<Awaited<ReturnType<BackupBeyondUseTaskRepository['listBackupBeyondUseTasks']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBackupBeyondUseTasks(input);
  }

  async createBackupBeyondUseTask(input: Parameters<BackupBeyondUseTaskRepository['createBackupBeyondUseTask']>[0]): Promise<Awaited<ReturnType<BackupBeyondUseTaskRepository['createBackupBeyondUseTask']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createBackupBeyondUseTask(input);
  }
}
