/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./backup-beyond-use-task-repository.ddb.js";
export * from "./complete-repository.ddb.js";
export * from "./live-erasure-task-repository.ddb.js";
export * from "./recipient-notice-repository.ddb.js";
export * from "./backup-beyond-use-task-repository.adapter.js";
export * from "./complete-repository.adapter.js";
export * from "./live-erasure-task-repository.adapter.js";
export * from "./recipient-notice-repository.adapter.js";
