/**
 * LiveErasureTaskRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LiveErasureTaskRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LiveErasureTaskRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LiveErasureTaskRepository,
} from "@forgetcase/services/fulfilment";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LiveErasureTaskRepositoryDdb } from "./live-erasure-task-repository.ddb.js";

/**
 * LiveErasureTaskRepositoryAdapter
 *
 * Implements LiveErasureTaskRepository port for infrastructure layer.
 */
export class LiveErasureTaskRepositoryAdapter implements LiveErasureTaskRepository {
  private readonly ddb: LiveErasureTaskRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LiveErasureTaskRepositoryDdb(this.dynamoClient);
  }

  async listLiveErasureTasks(input: Parameters<LiveErasureTaskRepository['listLiveErasureTasks']>[0]): Promise<Awaited<ReturnType<LiveErasureTaskRepository['listLiveErasureTasks']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listLiveErasureTasks(input);
  }

  async createLiveErasureTask(input: Parameters<LiveErasureTaskRepository['createLiveErasureTask']>[0]): Promise<Awaited<ReturnType<LiveErasureTaskRepository['createLiveErasureTask']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createLiveErasureTask(input);
  }
}
