/**
 * RecipientNoticeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RecipientNoticeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RecipientNoticeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RecipientNoticeRepository,
} from "@forgetcase/services/fulfilment";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RecipientNoticeRepositoryDdb } from "./recipient-notice-repository.ddb.js";

/**
 * RecipientNoticeRepositoryAdapter
 *
 * Implements RecipientNoticeRepository port for infrastructure layer.
 */
export class RecipientNoticeRepositoryAdapter implements RecipientNoticeRepository {
  private readonly ddb: RecipientNoticeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RecipientNoticeRepositoryDdb(this.dynamoClient);
  }

  async listRecipientNotices(input: Parameters<RecipientNoticeRepository['listRecipientNotices']>[0]): Promise<Awaited<ReturnType<RecipientNoticeRepository['listRecipientNotices']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listRecipientNotices(input);
  }

  async createRecipientNotice(input: Parameters<RecipientNoticeRepository['createRecipientNotice']>[0]): Promise<Awaited<ReturnType<RecipientNoticeRepository['createRecipientNotice']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createRecipientNotice(input);
  }

  async updateRecipientNotice(input: Parameters<RecipientNoticeRepository['updateRecipientNotice']>[0]): Promise<Awaited<ReturnType<RecipientNoticeRepository['updateRecipientNotice']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateRecipientNotice(input);
  }
}
