/**
 * RecipientNoticeRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RecipientNoticeRepositoryDdb
 *
 * DDD: Infrastructure adapter for RecipientNotice repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { RecipientNoticeRepository } from "@forgetcase/services/fulfilment";

export class RecipientNoticeRepositoryDdb implements RecipientNoticeRepository {
  constructor(private readonly dynamoClient: any) {}

  async listRecipientNotices(input: Parameters<RecipientNoticeRepository['listRecipientNotices']>[0]): Promise<Awaited<ReturnType<RecipientNoticeRepository['listRecipientNotices']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async createRecipientNotice(input: Parameters<RecipientNoticeRepository['createRecipientNotice']>[0]): Promise<Awaited<ReturnType<RecipientNoticeRepository['createRecipientNotice']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async updateRecipientNotice(input: Parameters<RecipientNoticeRepository['updateRecipientNotice']>[0]): Promise<Awaited<ReturnType<RecipientNoticeRepository['updateRecipientNotice']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
