/**
 * ExecuteSendCaseCorrespondence - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: correspondence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSendCaseCorrespondence Use Case
 *
 * DDD: Application use case for create Correspondence.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SendCaseCorrespondenceInput, SendCaseCorrespondenceOutput } from "../dto/correspondence.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { CorrespondenceRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteSendCaseCorrespondence {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly correspondence: CorrespondenceRepository
  ) {}

  async execute(input: SendCaseCorrespondenceInput): Promise<SendCaseCorrespondenceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.crdId();

    // All field names extracted from OpenAPI spec: body, channel, includesBackupHonesty, includesIcoComplaintRights, includesJudicialRemedy, includesReasons, templateType
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.includesJudicialRemedy) {
      throw new ValidationError("includesJudicialRemedy is required");
    }
    if (!input.includesReasons) {
      throw new ValidationError("includesReasons is required");
    }
    if (!input.includesIcoComplaintRights) {
      throw new ValidationError("includesIcoComplaintRights is required");
    }
    if (!input.templateType) {
      throw new ValidationError("templateType is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (correspondence domain)
    const entityId = this.idGenerator.crdId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.correspondence.sendCaseCorrespondence({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as SendCaseCorrespondenceOutput;
  }
}
