/**
 * ExecuteListCaseCorrespondence - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: correspondence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCaseCorrespondence Use Case
 *
 * DDD: Application use case for list Correspondence.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCaseCorrespondenceInput, ListCaseCorrespondenceOutput } from "../dto/correspondence.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { CorrespondenceRepository } from "../ports";

export class ExecuteListCaseCorrespondence {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly correspondence: CorrespondenceRepository
  ) {}

  async execute(input: ListCaseCorrespondenceInput): Promise<ListCaseCorrespondenceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.crdId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.correspondence.listCaseCorrespondence({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCaseCorrespondenceOutput;
  }
}
