/**
 * BackupBeyondUseTaskRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BackupBeyondUseTaskRepository Port
 *
 * DDD: Application port for backupbeyondusetaskrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateBackupBeyondUseTaskInput, CreateBackupBeyondUseTaskOutput, ListBackupBeyondUseTasksInput, ListBackupBeyondUseTasksOutput } from "../dto/backup-beyond-use-task.dto";
export interface BackupBeyondUseTaskRepository {
  listBackupBeyondUseTasks(input: ListBackupBeyondUseTasksInput): Promise<ListBackupBeyondUseTasksOutput>;
  createBackupBeyondUseTask(input: CreateBackupBeyondUseTaskInput): Promise<CreateBackupBeyondUseTaskOutput>;
}

export type { CreateBackupBeyondUseTaskInput, CreateBackupBeyondUseTaskOutput, ListBackupBeyondUseTasksInput, ListBackupBeyondUseTasksOutput } from "../dto/backup-beyond-use-task.dto";
