/**
 * CompleteRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompleteRepository Port
 *
 * DDD: Application port for completerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CompleteBackupBeyondUseTaskInput, CompleteBackupBeyondUseTaskOutput, CompleteLiveErasureTaskInput, CompleteLiveErasureTaskOutput } from "../dto/complete.dto";
export interface CompleteRepository {
  completeLiveErasureTask(input: CompleteLiveErasureTaskInput): Promise<CompleteLiveErasureTaskOutput>;
  completeBackupBeyondUseTask(input: CompleteBackupBeyondUseTaskInput): Promise<CompleteBackupBeyondUseTaskOutput>;
}

export type { CompleteBackupBeyondUseTaskInput, CompleteBackupBeyondUseTaskOutput, CompleteLiveErasureTaskInput, CompleteLiveErasureTaskOutput } from "../dto/complete.dto";
