/**
 * LiveErasureTaskRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LiveErasureTaskRepository Port
 *
 * DDD: Application port for liveerasuretaskrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateLiveErasureTaskInput, CreateLiveErasureTaskOutput, ListLiveErasureTasksInput, ListLiveErasureTasksOutput } from "../dto/live-erasure-task.dto";
export interface LiveErasureTaskRepository {
  listLiveErasureTasks(input: ListLiveErasureTasksInput): Promise<ListLiveErasureTasksOutput>;
  createLiveErasureTask(input: CreateLiveErasureTaskInput): Promise<CreateLiveErasureTaskOutput>;
}

export type { CreateLiveErasureTaskInput, CreateLiveErasureTaskOutput, ListLiveErasureTasksInput, ListLiveErasureTasksOutput } from "../dto/live-erasure-task.dto";
