/**
 * RecipientNoticeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RecipientNoticeRepository Port
 *
 * DDD: Application port for recipientnoticerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateRecipientNoticeInput, CreateRecipientNoticeOutput, ListRecipientNoticesInput, ListRecipientNoticesOutput, UpdateRecipientNoticeInput, UpdateRecipientNoticeOutput } from "../dto/recipient-notice.dto";
export interface RecipientNoticeRepository {
  listRecipientNotices(input: ListRecipientNoticesInput): Promise<ListRecipientNoticesOutput>;
  createRecipientNotice(input: CreateRecipientNoticeInput): Promise<CreateRecipientNoticeOutput>;
  updateRecipientNotice(input: UpdateRecipientNoticeInput): Promise<UpdateRecipientNoticeOutput>;
}

export type { CreateRecipientNoticeInput, CreateRecipientNoticeOutput, ListRecipientNoticesInput, ListRecipientNoticesOutput, UpdateRecipientNoticeInput, UpdateRecipientNoticeOutput } from "../dto/recipient-notice.dto";
