/**
 * AssessmentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssessmentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AssessmentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AssessmentRepository,
} from "@forgetcase/services/assessments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AssessmentRepositoryDdb } from "./assessment-repository.ddb.js";

/**
 * AssessmentRepositoryAdapter
 *
 * Implements AssessmentRepository port for infrastructure layer.
 */
export class AssessmentRepositoryAdapter implements AssessmentRepository {
  private readonly ddb: AssessmentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AssessmentRepositoryDdb(this.dynamoClient);
  }

  async getGroundAssessment(input: Parameters<AssessmentRepository['getGroundAssessment']>[0]): Promise<Awaited<ReturnType<AssessmentRepository['getGroundAssessment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getGroundAssessment(input);
  }

  async submitGroundAssessment(input: Parameters<AssessmentRepository['submitGroundAssessment']>[0]): Promise<Awaited<ReturnType<AssessmentRepository['submitGroundAssessment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitGroundAssessment(input);
  }
}
