/**
 * ExemptionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExemptionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExemptionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExemptionRepository,
} from "@forgetcase/services/assessments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExemptionRepositoryDdb } from "./exemption-repository.ddb.js";

/**
 * ExemptionRepositoryAdapter
 *
 * Implements ExemptionRepository port for infrastructure layer.
 */
export class ExemptionRepositoryAdapter implements ExemptionRepository {
  private readonly ddb: ExemptionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExemptionRepositoryDdb(this.dynamoClient);
  }

  async listExemptions(input: Parameters<ExemptionRepository['listExemptions']>[0]): Promise<Awaited<ReturnType<ExemptionRepository['listExemptions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listExemptions(input);
  }

  async applyExemption(input: Parameters<ExemptionRepository['applyExemption']>[0]): Promise<Awaited<ReturnType<ExemptionRepository['applyExemption']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.applyExemption(input);
  }
}
