/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Sla Domain Use Cases
 * 
 * List of all use case names for the sla domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SLA_USE_CASES = [
  "executeExtendSlaClock",
  "executeGetSlaClock",
  "executeRequestIdentityChallenge",
  "executeSatisfyIdentityChallenge"
] as const;
