/**
 * ExecuteUpdateRecipientNotice - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateRecipientNotice Use Case
 *
 * DDD: Application use case for update RecipientNotice.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateRecipientNoticeInput, UpdateRecipientNoticeOutput } from "../dto/recipient-notice.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { RecipientNoticeRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateRecipientNotice {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly recipientNotice: RecipientNoticeRepository
  ) {}

  async execute(input: UpdateRecipientNoticeInput): Promise<UpdateRecipientNoticeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fflId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).caseId) {
      throw new ValidationError("caseId is required");
    }
    const caseId = (input as any).caseId;

    // Load existing entity
    const listResult = await this.recipientNotice.listRecipientNotices({ orgId: this.context.getOrgId(), correlationId } as any);
    const listItems = Array.isArray((listResult as any)?.data?.items)
      ? (listResult as any).data.items
      : (Array.isArray((listResult as any)?.data) ? (listResult as any).data : []);
    const existing = listItems.find((item: any) => (item?.id ?? item?.['caseId']) == caseId);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${caseId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.recipientNotice.updateRecipientNotice({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateRecipientNoticeOutput;
  }
}
