/**
 * ExecuteCreateBackupBeyondUseTask - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateBackupBeyondUseTask Use Case
 *
 * DDD: Application use case for create BackupBeyondUseTask.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateBackupBeyondUseTaskInput, CreateBackupBeyondUseTaskOutput } from "../dto/backup-beyond-use-task.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { BackupBeyondUseTaskRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateBackupBeyondUseTask {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly backupBeyondUseTask: BackupBeyondUseTaskRepository
  ) {}

  async execute(input: CreateBackupBeyondUseTaskInput): Promise<CreateBackupBeyondUseTaskOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fflId();

    // All field names extracted from OpenAPI spec: backupSystem, caseId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.caseId) {
      throw new ValidationError("caseId is required");
    }
    if (!input.backupSystem) {
      throw new ValidationError("backupSystem is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (fulfilment domain)
    const entityId = this.idGenerator.fflId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.backupBeyondUseTask.createBackupBeyondUseTask({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateBackupBeyondUseTaskOutput;
  }
}
