/**
 * ExecuteListLiveErasureTasks - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListLiveErasureTasks Use Case
 *
 * DDD: Application use case for list LiveErasureTask.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListLiveErasureTasksInput, ListLiveErasureTasksOutput } from "../dto/live-erasure-task.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { LiveErasureTaskRepository } from "../ports";

export class ExecuteListLiveErasureTasks {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly liveErasureTask: LiveErasureTaskRepository
  ) {}

  async execute(input: ListLiveErasureTasksInput): Promise<ListLiveErasureTasksOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fflId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.liveErasureTask.listLiveErasureTasks({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListLiveErasureTasksOutput;
  }
}
