/**
 * ExecuteListBackupBeyondUseTasks - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListBackupBeyondUseTasks Use Case
 *
 * DDD: Application use case for list BackupBeyondUseTask.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListBackupBeyondUseTasksInput, ListBackupBeyondUseTasksOutput } from "../dto/backup-beyond-use-task.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { BackupBeyondUseTaskRepository } from "../ports";

export class ExecuteListBackupBeyondUseTasks {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly backupBeyondUseTask: BackupBeyondUseTaskRepository
  ) {}

  async execute(input: ListBackupBeyondUseTasksInput): Promise<ListBackupBeyondUseTasksOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fflId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.backupBeyondUseTask.listBackupBeyondUseTasks({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListBackupBeyondUseTasksOutput;
  }
}
