/**
 * ExecuteListRecipientNotices - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListRecipientNotices Use Case
 *
 * DDD: Application use case for list RecipientNotice.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListRecipientNoticesInput, ListRecipientNoticesOutput } from "../dto/recipient-notice.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { RecipientNoticeRepository } from "../ports";

export class ExecuteListRecipientNotices {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly recipientNotice: RecipientNoticeRepository
  ) {}

  async execute(input: ListRecipientNoticesInput): Promise<ListRecipientNoticesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fflId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.recipientNotice.listRecipientNotices({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListRecipientNoticesOutput;
  }
}
