/**
 * Handlers for BackupBeyondUseTask
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { FulfilmentDomainModule } from "../dependencies/fulfilment-ddd.dependencies.js";
import type { CreateBackupBeyondUseTaskInput, ListBackupBeyondUseTasksInput } from "@forgetcase/services/fulfilment";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/backup-beyond-use-tasks
 * Operation: listBackupBeyondUseTasks
 */
export async function listBackupBeyondUseTasks(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], caseId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: FulfilmentDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListBackupBeyondUseTasksInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.backupBeyondUseTasks.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/backup-beyond-use-tasks
 * Operation: createBackupBeyondUseTask
 */
export async function createBackupBeyondUseTask(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: FulfilmentDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateBackupBeyondUseTaskInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.backupBeyondUseTasks.create.execute(input);
  return reply.code(201).send(result);
}


