/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./backup-beyond-use-task.handlers.js";
export * from "./complete.handlers.js";
export * from "./live-erasure-task.handlers.js";
export * from "./recipient-notice.handlers.js";
