/**
 * Handlers for LiveErasureTask
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { FulfilmentDomainModule } from "../dependencies/fulfilment-ddd.dependencies.js";
import type { CreateLiveErasureTaskInput, ListLiveErasureTasksInput } from "@forgetcase/services/fulfilment";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/erasure-cases/{caseId}/live-erasure-tasks
 * Operation: listLiveErasureTasks
 */
export async function listLiveErasureTasks(
  request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: FulfilmentDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListLiveErasureTasksInput = {
    caseId: request.params.caseId,
  };
  const result = await deps.useCases.liveErasureTasks.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/erasure-cases/{caseId}/live-erasure-tasks
 * Operation: createLiveErasureTask
 */
export async function createLiveErasureTask(
  request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: FulfilmentDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateLiveErasureTaskInput = {
    caseId: request.params.caseId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.liveErasureTasks.create.execute(input);
  return reply.code(201).send(result);
}


