/**
 * Handlers for RecipientNotice
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { FulfilmentDomainModule } from "../dependencies/fulfilment-ddd.dependencies.js";
import type { CreateRecipientNoticeInput, ListRecipientNoticesInput, UpdateRecipientNoticeInput } from "@forgetcase/services/fulfilment";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/erasure-cases/{caseId}/recipient-notices
 * Operation: listRecipientNotices
 */
export async function listRecipientNotices(
  request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: FulfilmentDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListRecipientNoticesInput = {
    caseId: request.params.caseId,
  };
  const result = await deps.useCases.recipientNotices.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/erasure-cases/{caseId}/recipient-notices
 * Operation: createRecipientNotice
 */
export async function createRecipientNotice(
  request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: FulfilmentDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateRecipientNoticeInput = {
    caseId: request.params.caseId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.recipientNotices.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for PATCH /v1/recipient-notices/{noticeId}
 * Operation: updateRecipientNotice
 */
export async function updateRecipientNotice(
  request: FastifyRequest<{ Params: { noticeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: FulfilmentDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateRecipientNoticeInput = {
    noticeId: request.params.noticeId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.recipientNotices.update.execute(input);
  return reply.code(200).send(result);
}


