/**
 * GetSla DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetSlaClockParams } from "@forgetcase/core/sla";

export function createGetSlaRequest(overrides: Partial<GetSlaClockParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
