/**
 * BackupBeyondUseTask Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/fulfilment.openapi.types.js";
import { schemas } from "../schemas/fulfilment.schemas.js";

/**
 * Entity: BackupBeyondUseTaskEntity
 * Description: Represents the BackupBeyondUseTask domain model.
 * Source: schemas.BackupBeyondUseTask
 * Type: Domain Entity (API)
 */
export const BackupBeyondUseTaskEntitySchema = schemas.BackupBeyondUseTask;
export type BackupBeyondUseTaskEntity = components["schemas"]["BackupBeyondUseTask"];
