/**
 * LiveErasureTask Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/fulfilment.openapi.types.js";
import { schemas } from "../schemas/fulfilment.schemas.js";

/**
 * Entity: LiveErasureTaskEntity
 * Description: Represents the LiveErasureTask domain model.
 * Source: schemas.LiveErasureTask
 * Type: Domain Entity (API)
 */
export const LiveErasureTaskEntitySchema = schemas.LiveErasureTask;
export type LiveErasureTaskEntity = components["schemas"]["LiveErasureTask"];
