/**
 * RecipientNotice Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/fulfilment.openapi.types.js";
import { schemas } from "../schemas/fulfilment.schemas.js";

/**
 * Entity: RecipientNoticeEntity
 * Description: Represents the RecipientNotice domain model.
 * Source: schemas.RecipientNotice
 * Type: Domain Entity (API)
 */
export const RecipientNoticeEntitySchema = schemas.RecipientNotice;
export type RecipientNoticeEntity = components["schemas"]["RecipientNotice"];
