/**
 * RequestIdentityChallenge handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { requestIdentityChallenge } from "@forgetcase/api-server/domains/sla/handlers";
import type { SlaDDDDependencies } from "@forgetcase/api-server/domains/sla";
import { createIdentityChallenge as createIdentityChallengeEntity } from "@forgetcase/factories/sla";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@forgetcase/tests/shared";
import { SLA_USE_CASES } from "../__factories__/use-cases.js";

describe("RequestIdentityChallenge", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SlaDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SlaDDDDependencies>(
      SLA_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createIdentityChallengeEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRequestIdentityChallenge, "execute").mockResolvedValue(useCaseResult);

    await requestIdentityChallenge(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRequestIdentityChallenge.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
