/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAssessmentsDomainModule } from "./assessments/dependencies/assessments-ddd.dependencies.js";
export { buildCasesDomainModule } from "./cases/dependencies/cases-ddd.dependencies.js";
export { buildCorrespondenceDomainModule } from "./correspondence/dependencies/correspondence-ddd.dependencies.js";
export { buildFulfilmentDomainModule } from "./fulfilment/dependencies/fulfilment-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildSlaDomainModule } from "./sla/dependencies/sla-ddd.dependencies.js";

// Export all domain dependency types
export type { AssessmentsDomainModule } from "./assessments/dependencies/assessments-ddd.dependencies.js";
export type { CasesDomainModule } from "./cases/dependencies/cases-ddd.dependencies.js";
export type { CorrespondenceDomainModule } from "./correspondence/dependencies/correspondence-ddd.dependencies.js";
export type { FulfilmentDomainModule } from "./fulfilment/dependencies/fulfilment-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { SlaDomainModule } from "./sla/dependencies/sla-ddd.dependencies.js";
