/**
 * IntakeEventRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IntakeEventRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements IntakeEventRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  IntakeEventRepository,
} from "@forgetcase/services/cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { IntakeEventRepositoryDdb } from "./intake-event-repository.ddb.js";

/**
 * IntakeEventRepositoryAdapter
 *
 * Implements IntakeEventRepository port for infrastructure layer.
 */
export class IntakeEventRepositoryAdapter implements IntakeEventRepository {
  private readonly ddb: IntakeEventRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new IntakeEventRepositoryDdb(this.dynamoClient);
  }

  async listCaseIntakeEvents(input: Parameters<IntakeEventRepository['listCaseIntakeEvents']>[0]): Promise<Awaited<ReturnType<IntakeEventRepository['listCaseIntakeEvents']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCaseIntakeEvents(input);
  }
}
