/**
 * VerbalRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VerbalRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VerbalRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VerbalRepository,
} from "@forgetcase/services/cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VerbalRepositoryDdb } from "./verbal-repository.ddb.js";

/**
 * VerbalRepositoryAdapter
 *
 * Implements VerbalRepository port for infrastructure layer.
 */
export class VerbalRepositoryAdapter implements VerbalRepository {
  private readonly ddb: VerbalRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VerbalRepositoryDdb(this.dynamoClient);
  }

  async createVerbalIntake(input: Parameters<VerbalRepository['createVerbalIntake']>[0]): Promise<Awaited<ReturnType<VerbalRepository['createVerbalIntake']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createVerbalIntake(input);
  }
}
