/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { extensionRoutes } from "./extension.routes.js";
export { identityChallengeRoutes } from "./identity-challenge.routes.js";
export { satisfyRoutes } from "./satisfy.routes.js";
export { slaRoutes } from "./sla.routes.js";
