/**
 * Routes for Satisfy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { satisfyIdentityChallenge } from "../handlers/satisfy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function satisfyRoutes(fastify: FastifyInstance) {
  // POST /v1/erasure-cases/{caseId}/identity-challenge/satisfy (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/erasure-cases/:caseId/identity-challenge/satisfy",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSlaDependenciesForRequest();
        await satisfyIdentityChallenge(request, reply, deps);
      });
    }
  );


}
