/**
 * IntakeEvent Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/cases.openapi.types.js";
import { schemas } from "../schemas/cases.schemas.js";

/**
 * Entity: IntakeEventEntity
 * Description: Represents the IntakeEvent domain model.
 * Source: schemas.IntakeEvent
 * Type: Domain Entity (API)
 */
export const IntakeEventEntitySchema = schemas.IntakeEvent;
export type IntakeEventEntity = components["schemas"]["IntakeEvent"];
