/**
 * ExecuteApplyExemption - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assessments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteApplyExemption Use Case
 *
 * DDD: Application use case for get Exemption.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ApplyExemptionInput, ApplyExemptionOutput } from "../dto/exemption.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { ExemptionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteApplyExemption {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exemption: ExemptionRepository
  ) {}

  async execute(input: ApplyExemptionInput): Promise<ApplyExemptionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.asmId();

    // All field names extracted from OpenAPI spec: exemptionType, feeAmount, feeBasis, rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).caseId) {
      throw new ValidationError("caseId is required");
    }
    const caseId = (input as any).caseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.exemption.applyExemption({ caseId: caseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${caseId}`);
    }

    return entity as ApplyExemptionOutput;
  }
}
