/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@forgetcase/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@forgetcase/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@forgetcase/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _assessments from "./assessments/index.js";
import * as _cases from "./cases/index.js";
import * as _correspondence from "./correspondence/index.js";
import * as _fulfilment from "./fulfilment/index.js";
import * as _identity from "./identity/index.js";
import * as _sla from "./sla/index.js";

// Export as namespaces
export const assessments = _assessments;
export const cases = _cases;
export const correspondence = _correspondence;
export const fulfilment = _fulfilment;
export const identity = _identity;
export const sla = _sla;
