/**
 * Handlers for Sla
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SlaDomainModule } from "../dependencies/sla-ddd.dependencies.js";
import type { GetSlaClockInput } from "@forgetcase/services/sla";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/erasure-cases/{caseId}/sla
 * Operation: getSlaClock
 */
export async function getSlaClock(
  request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SlaDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSlaClockInput = {
    caseId: request.params.caseId,
  };
  const result = await deps.useCases.slas.get.execute(input);
  return reply.code(200).send(result);
}


