/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the fulfilment domain.
 * Use these factories in tests to create test data.
 */

export { createBackupBeyondUseTask } from "./backup-beyond-use-task/entity/backup-beyond-use-task.entity.factory.js";
export { createLiveErasureTask } from "./live-erasure-task/entity/live-erasure-task.entity.factory.js";
export { createRecipientNotice } from "./recipient-notice/entity/recipient-notice.entity.factory.js";
