/**
 * ExtensionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExtensionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExtensionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExtensionRepository,
} from "@forgetcase/services/sla";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExtensionRepositoryDdb } from "./extension-repository.ddb.js";

/**
 * ExtensionRepositoryAdapter
 *
 * Implements ExtensionRepository port for infrastructure layer.
 */
export class ExtensionRepositoryAdapter implements ExtensionRepository {
  private readonly ddb: ExtensionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExtensionRepositoryDdb(this.dynamoClient);
  }

  async extendSlaClock(input: Parameters<ExtensionRepository['extendSlaClock']>[0]): Promise<Awaited<ReturnType<ExtensionRepository['extendSlaClock']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.extendSlaClock(input);
  }
}
