/**
 * IdentityChallengeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IdentityChallengeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements IdentityChallengeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  IdentityChallengeRepository,
} from "@forgetcase/services/sla";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { IdentityChallengeRepositoryDdb } from "./identity-challenge-repository.ddb.js";

/**
 * IdentityChallengeRepositoryAdapter
 *
 * Implements IdentityChallengeRepository port for infrastructure layer.
 */
export class IdentityChallengeRepositoryAdapter implements IdentityChallengeRepository {
  private readonly ddb: IdentityChallengeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new IdentityChallengeRepositoryDdb(this.dynamoClient);
  }

  async requestIdentityChallenge(input: Parameters<IdentityChallengeRepository['requestIdentityChallenge']>[0]): Promise<Awaited<ReturnType<IdentityChallengeRepository['requestIdentityChallenge']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.requestIdentityChallenge(input);
  }
}
