/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./extension-repository.ddb.js";
export * from "./identity-challenge-repository.ddb.js";
export * from "./satisfy-repository.ddb.js";
export * from "./sla-repository.ddb.js";
export * from "./extension-repository.adapter.js";
export * from "./identity-challenge-repository.adapter.js";
export * from "./satisfy-repository.adapter.js";
export * from "./sla-repository.adapter.js";
