/**
 * SatisfyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SatisfyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SatisfyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SatisfyRepository,
} from "@forgetcase/services/sla";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SatisfyRepositoryDdb } from "./satisfy-repository.ddb.js";

/**
 * SatisfyRepositoryAdapter
 *
 * Implements SatisfyRepository port for infrastructure layer.
 */
export class SatisfyRepositoryAdapter implements SatisfyRepository {
  private readonly ddb: SatisfyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SatisfyRepositoryDdb(this.dynamoClient);
  }

  async satisfyIdentityChallenge(input: Parameters<SatisfyRepository['satisfyIdentityChallenge']>[0]): Promise<Awaited<ReturnType<SatisfyRepository['satisfyIdentityChallenge']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.satisfyIdentityChallenge(input);
  }
}
