/**
 * SlaRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SlaRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SlaRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SlaRepository,
} from "@forgetcase/services/sla";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SlaRepositoryDdb } from "./sla-repository.ddb.js";

/**
 * SlaRepositoryAdapter
 *
 * Implements SlaRepository port for infrastructure layer.
 */
export class SlaRepositoryAdapter implements SlaRepository {
  private readonly ddb: SlaRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SlaRepositoryDdb(this.dynamoClient);
  }

  async getSlaClock(input: Parameters<SlaRepository['getSlaClock']>[0]): Promise<Awaited<ReturnType<SlaRepository['getSlaClock']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSlaClock(input);
  }
}
