/**
 * ExtensionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExtensionRepository Port
 *
 * DDD: Application port for extensionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExtendSlaClockInput, ExtendSlaClockOutput } from "../dto/extension.dto";
export interface ExtensionRepository {
  extendSlaClock(input: ExtendSlaClockInput): Promise<ExtendSlaClockOutput>;
}

export type { ExtendSlaClockInput, ExtendSlaClockOutput } from "../dto/extension.dto";
