/**
 * IdentityChallengeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IdentityChallengeRepository Port
 *
 * DDD: Application port for identitychallengerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RequestIdentityChallengeInput, RequestIdentityChallengeOutput } from "../dto/identity-challenge.dto";
export interface IdentityChallengeRepository {
  requestIdentityChallenge(input: RequestIdentityChallengeInput): Promise<RequestIdentityChallengeOutput>;
}

export type { RequestIdentityChallengeInput, RequestIdentityChallengeOutput } from "../dto/identity-challenge.dto";
