/**
 * SatisfyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SatisfyRepository Port
 *
 * DDD: Application port for satisfyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SatisfyIdentityChallengeInput, SatisfyIdentityChallengeOutput } from "../dto/satisfy.dto";
export interface SatisfyRepository {
  satisfyIdentityChallenge(input: SatisfyIdentityChallengeInput): Promise<SatisfyIdentityChallengeOutput>;
}

export type { SatisfyIdentityChallengeInput, SatisfyIdentityChallengeOutput } from "../dto/satisfy.dto";
