/**
 * CorrespondenceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: correspondence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CorrespondenceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CorrespondenceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CorrespondenceRepository,
} from "@forgetcase/services/correspondence";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CorrespondenceRepositoryDdb } from "./correspondence-repository.ddb.js";

/**
 * CorrespondenceRepositoryAdapter
 *
 * Implements CorrespondenceRepository port for infrastructure layer.
 */
export class CorrespondenceRepositoryAdapter implements CorrespondenceRepository {
  private readonly ddb: CorrespondenceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CorrespondenceRepositoryDdb(this.dynamoClient);
  }

  async listCaseCorrespondence(input: Parameters<CorrespondenceRepository['listCaseCorrespondence']>[0]): Promise<Awaited<ReturnType<CorrespondenceRepository['listCaseCorrespondence']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCaseCorrespondence(input);
  }

  async sendCaseCorrespondence(input: Parameters<CorrespondenceRepository['sendCaseCorrespondence']>[0]): Promise<Awaited<ReturnType<CorrespondenceRepository['sendCaseCorrespondence']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.sendCaseCorrespondence(input);
  }
}
