/**
 * IdentityChallenge Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/sla.openapi.types.js";
import { schemas } from "../schemas/sla.schemas.js";

/**
 * Entity: IdentityChallengeEntity
 * Description: Represents the IdentityChallenge domain model.
 * Source: schemas.IdentityChallenge
 * Type: Domain Entity (API)
 */
export const IdentityChallengeEntitySchema = schemas.IdentityChallenge;
export type IdentityChallengeEntity = components["schemas"]["IdentityChallenge"];
