/**
 * Repository interface for BackupBeyondUseTask
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  BackupBeyondUseTaskEntity
} from "../models/backup-beyond-use-task.entity.js";
import type {
  ListBackupBeyondUseTasksParams,
  BackupBeyondUseTask
} from "../types/index.js";
/**
 * BackupBeyondUseTaskRepository Interface
 */
export interface BackupBeyondUseTaskRepository extends CreateReadRepository<BackupBeyondUseTaskEntity, BackupBeyondUseTask, string, ListBackupBeyondUseTasksParams> {

}
