/**
 * Correspondence DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: correspondence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Correspondence DTOs
 *
 * DDD: Application DTOs for Correspondence use cases.
 */

import type { ListCaseCorrespondenceParams, SendCaseCorrespondenceParams, SendCaseCorrespondenceRequestInput } from "@forgetcase/core/correspondence/types";

export type ListCaseCorrespondenceInput = ListCaseCorrespondenceParams;

export type SendCaseCorrespondenceInput = SendCaseCorrespondenceParams & SendCaseCorrespondenceRequestInput;

export type ListCaseCorrespondenceOutput = {};

export type SendCaseCorrespondenceOutput = {};
