/**
 * CorrespondenceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: correspondence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CorrespondenceRepository Port
 *
 * DDD: Application port for correspondencerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListCaseCorrespondenceInput, ListCaseCorrespondenceOutput, SendCaseCorrespondenceInput, SendCaseCorrespondenceOutput } from "../dto/correspondence.dto";
export interface CorrespondenceRepository {
  listCaseCorrespondence(input: ListCaseCorrespondenceInput): Promise<ListCaseCorrespondenceOutput>;
  sendCaseCorrespondence(input: SendCaseCorrespondenceInput): Promise<SendCaseCorrespondenceOutput>;
}

export type { ListCaseCorrespondenceInput, ListCaseCorrespondenceOutput, SendCaseCorrespondenceInput, SendCaseCorrespondenceOutput } from "../dto/correspondence.dto";
