/**
 * Handlers for ErasureCase
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CasesDomainModule } from "../dependencies/cases-ddd.dependencies.js";
import type { CreateErasureCaseInput, GetErasureCaseInput, ListErasureCasesInput } from "@forgetcase/services/cases";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/erasure-cases
 * Operation: listErasureCases
 */
export async function listErasureCases(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], childDataWeight?: string | string[], idPaused?: string | string[], slaRisk?: string | string[], channel?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListErasureCasesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.erasureCases.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/erasure-cases
 * Operation: createErasureCase
 */
export async function createErasureCase(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateErasureCaseInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.erasureCases.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/erasure-cases/{caseId}
 * Operation: getErasureCase
 */
export async function getErasureCase(
  request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetErasureCaseInput = {
    caseId: request.params.caseId,
  };
  const result = await deps.useCases.erasureCases.get.execute(input);
  return reply.code(200).send(result);
}


