/**
 * Handlers for Export
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CasesDomainModule } from "../dependencies/cases-ddd.dependencies.js";
import type { CreateAuditExportInput } from "@forgetcase/services/cases";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/audit/exports
 * Operation: createAuditExport
 */
export async function createAuditExport(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateAuditExportInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.exports.create.execute(input);
  return reply.code(201).send(result);
}


