/**
 * Routes for ErasureCase
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createErasureCase, getErasureCase, listErasureCases } from "../handlers/erasure-case.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function erasureCaseRoutes(fastify: FastifyInstance) {
  // POST /v1/erasure-cases (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/erasure-cases",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCasesDependenciesForRequest();
        await createErasureCase(request, reply, deps);
      });
    }
  );


  // GET /v1/erasure-cases (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/erasure-cases",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCasesDependenciesForRequest();
        await listErasureCases(request, reply, deps);
      });
    }
  );


  // GET /v1/erasure-cases/{caseId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/erasure-cases/:caseId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCasesDependenciesForRequest();
        await getErasureCase(request, reply, deps);
      });
    }
  );


}
