/**
 * Routes for IntakeEvent
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listCaseIntakeEvents } from "../handlers/intake-event.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function intakeEventRoutes(fastify: FastifyInstance) {
  // GET /v1/erasure-cases/{caseId}/intake-events (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/erasure-cases/:caseId/intake-events",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCasesDependenciesForRequest();
        await listCaseIntakeEvents(request, reply, deps);
      });
    }
  );


}
