/**
 * Sla DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Sla Domain Module - Composition root
 *
 * DDD: Composition root for sla domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ExtensionRepositoryAdapter,
  IdentityChallengeRepositoryAdapter,
  SatisfyRepositoryAdapter,
  SlaRepositoryAdapter,
} from "@forgetcase/adapters/sla";
import { getIdGeneratorService } from "@forgetcase/adapters";
import type { AdapterDynamoDBClient } from "@forgetcase/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteExtendSlaClock,
  ExecuteGetSlaClock,
  ExecuteRequestIdentityChallenge,
  ExecuteSatisfyIdentityChallenge,
} from "@forgetcase/services/sla/usecases";
// Ports (interfaces)
import type {
  ExtensionRepository,
  IdentityChallengeRepository,
  SatisfyRepository,
  SlaRepository,
} from "@forgetcase/services/sla/ports";

export interface SlaDomainModule {
  repos: {
    extensions: ExtensionRepository;
    identityChallenges: IdentityChallengeRepository;
    satisfies: SatisfyRepository;
    slas: SlaRepository;
  };
  useCases: {
    extensions: {
      get: ExecuteExtendSlaClock;
    };
    identityChallenges: {
      get: ExecuteRequestIdentityChallenge;
    };
    satisfies: {
      get: ExecuteSatisfyIdentityChallenge;
    };
    slas: {
      get: ExecuteGetSlaClock;
    };
  };
}

export function buildSlaDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SlaDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      extensions?: ExtensionRepository;
      identityChallenges?: IdentityChallengeRepository;
      satisfies?: SatisfyRepository;
      slas?: SlaRepository;
    } = {};

    obj.extensions = new ExtensionRepositoryAdapter(dynamoClient);
    obj.identityChallenges = new IdentityChallengeRepositoryAdapter(dynamoClient);
    obj.satisfies = new SatisfyRepositoryAdapter(dynamoClient);
    obj.slas = new SlaRepositoryAdapter(dynamoClient);
    return {
      extensions: obj.extensions!,
      identityChallenges: obj.identityChallenges!,
      satisfies: obj.satisfies!,
      slas: obj.slas!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    extensions: {
      get: new ExecuteExtendSlaClock(executionContext, idGenerator, repos.extensions),
    },
    identityChallenges: {
      get: new ExecuteRequestIdentityChallenge(executionContext, idGenerator, repos.identityChallenges),
    },
    satisfies: {
      get: new ExecuteSatisfyIdentityChallenge(executionContext, idGenerator, repos.satisfies),
    },
    slas: {
      get: new ExecuteGetSlaClock(executionContext, idGenerator, repos.slas),
    },
  };
  return { repos, useCases: useCases as SlaDomainModule["useCases"] };
}
