/**
 * CompleteLiveErasureTask handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { completeLiveErasureTask } from "@forgetcase/api-server/domains/fulfilment/handlers";
import type { FulfilmentDDDDependencies } from "@forgetcase/api-server/domains/fulfilment";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@forgetcase/tests/shared";
import { FULFILMENT_USE_CASES } from "../__factories__/use-cases.js";

describe("CompleteLiveErasureTask", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FulfilmentDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FulfilmentDDDDependencies>(
      FULFILMENT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCompleteLiveErasureTask, "execute").mockResolvedValue(useCaseResult);

    await completeLiveErasureTask(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCompleteLiveErasureTask.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
