/**
 * ListRecipientNotices handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listRecipientNotices } from "@forgetcase/api-server/domains/fulfilment/handlers";
import type { FulfilmentDDDDependencies } from "@forgetcase/api-server/domains/fulfilment";
import { createRecipientNotice as createRecipientNoticeEntity } from "@forgetcase/factories/fulfilment";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@forgetcase/tests/shared";
import { FULFILMENT_USE_CASES } from "../__factories__/use-cases.js";

describe("ListRecipientNotices", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FulfilmentDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FulfilmentDDDDependencies>(
      FULFILMENT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createRecipientNoticeEntity({ orgId }),
      createRecipientNoticeEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListRecipientNotices, "execute").mockResolvedValue(useCaseResult);

    await listRecipientNotices(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListRecipientNotices.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
