/**
 * LiveErasureTask Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { LiveErasureTaskEntity } from "@forgetcase/core/fulfilment/models/index.js";
import { fulfilmentSchemas } from "@forgetcase/core/fulfilment";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ffl";

export function createLiveErasureTask(overrides: Partial<LiveErasureTaskEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    caseId: overrides.caseId ?? `cas_${ulid().toLowerCase()}`,
    status: overrides.status ?? "queued",
    systemName: overrides.systemName ?? faker.lorem.word(),
    taskId: overrides.taskId ?? `lvt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return fulfilmentSchemas.LiveErasureTask.parse(raw);
}

export function liveErasureTaskBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createLiveErasureTask(overrides));
}
