/**
 * ListBackupBeyondUseTask DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListBackupBeyondUseTasksParams } from "@forgetcase/core/fulfilment";

export function createListBackupBeyondUseTaskRequest(overrides: Partial<ListBackupBeyondUseTasksParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
