/**
 * Repository interface for IdentityChallenge
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  IdentityChallengeEntity
} from "../models/identity-challenge.entity.js";
import type {
  IdentityChallenge
} from "../types/index.js";
/**
 * IdentityChallengeRepository Interface
 */
export interface IdentityChallengeRepository extends CreateReadRepository<IdentityChallengeEntity, IdentityChallenge, string, Record<string, never>> {

}
