/**
 * ExecuteSatisfyIdentityChallenge - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSatisfyIdentityChallenge Use Case
 *
 * DDD: Application use case for get Satisfy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SatisfyIdentityChallengeInput, SatisfyIdentityChallengeOutput } from "../dto/satisfy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { SatisfyRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteSatisfyIdentityChallenge {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly satisfy: SatisfyRepository
  ) {}

  async execute(input: SatisfyIdentityChallengeInput): Promise<SatisfyIdentityChallengeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.slaId();

    // All field names extracted from OpenAPI spec: note
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).caseId) {
      throw new ValidationError("caseId is required");
    }
    const caseId = (input as any).caseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.satisfy.satisfyIdentityChallenge({ caseId: caseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${caseId}`);
    }

    return entity as SatisfyIdentityChallengeOutput;
  }
}
