/**
 * ExecuteExtendSlaClock - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sla
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteExtendSlaClock Use Case
 *
 * DDD: Application use case for get Extension.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ExtendSlaClockInput, ExtendSlaClockOutput } from "../dto/extension.dto";
import type { ExecutionContextService, IdGeneratorService } from "@forgetcase/services/_shared/index.js";
import type { ExtensionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteExtendSlaClock {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly extension: ExtensionRepository
  ) {}

  async execute(input: ExtendSlaClockInput): Promise<ExtendSlaClockOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.slaId();

    // All field names extracted from OpenAPI spec: additionalMonths, noticeDraft, reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).caseId) {
      throw new ValidationError("caseId is required");
    }
    const caseId = (input as any).caseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.extension.extendSlaClock({ caseId: caseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${caseId}`);
    }

    return entity as ExtendSlaClockOutput;
  }
}
